version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '24001:8025'

    mariadb:
        image: 'mariadb:11.0'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=password
            - MYSQL_USER=app
            - MYSQL_PASSWORD=password
        ports:
            - '24003:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '24000:80'

    php-fpm:
        build: ./php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
